Retry API connections and improve error messages
When `--retry-connections` is true (defaults to false), the following behavior
is enabled.

Resolves #6

Without this path, the backup fails hard and fast if puppetserver hasn't started
up fully.  This patch adds a connect timeout option.  All API requests are
retried until the specified timeout is reached.  Currently, the only exception
retried is [Errno::ECONNREFUSED].  Other exceptions may be added to the list if
necessary.  Unspecified exceptions will immediately abort the timeout and retry
and be thrown.

The retry logic has been copied from Cloud Provisioner.

This patch also adds a friendly error handler at the top of the application.

The user experiences the following by default:

    $ ncio --no-syslog backup
    ERROR: Timeout expired connecting to the console service.  Verify it is up and running.

And in the systemlog (redirected to stderr for convenience):

    $ ncio --no-syslog backup
    W, [2016-08-09T16:28:50.303845 #51400]  WARN -- : Starting Node Classification Backup using GET https://Jeff-McCune.local:4433/classifier-api/v1/groups
    W, [2016-08-09T16:28:50.306206 #51400]  WARN -- : Retrying: Errno::ECONNREFUSED: Connection refused - connect(2) for "Jeff-McCune.local" port 4433
    W, [2016-08-09T16:28:50.411498 #51400]  WARN -- : Retrying: Errno::ECONNREFUSED: Connection refused - connect(2) for "Jeff-McCune.local" port 4433
    W, [2016-08-09T16:28:50.715641 #51400]  WARN -- : Retrying: Errno::ECONNREFUSED: Connection refused - connect(2) for "Jeff-McCune.local" port 4433
    W, [2016-08-09T16:28:51.421242 #51400]  WARN -- : Retrying: Errno::ECONNREFUSED: Connection refused - connect(2) for "Jeff-McCune.local" port 4433
    W, [2016-08-09T16:28:52.926286 #51400]  WARN -- : Retrying: Errno::ECONNREFUSED: Connection refused - connect(2) for "Jeff-McCune.local" port 4433
    W, [2016-08-09T16:28:56.031902 #51400]  WARN -- : Retrying: Errno::ECONNREFUSED: Connection refused - connect(2) for "Jeff-McCune.local" port 4433
    W, [2016-08-09T16:29:02.337266 #51400]  WARN -- : Retrying: Errno::ECONNREFUSED: Connection refused - connect(2) for "Jeff-McCune.local" port 4433
    W, [2016-08-09T16:29:15.044361 #51400]  WARN -- : Retrying: Errno::ECONNREFUSED: Connection refused - connect(2) for "Jeff-McCune.local" port 4433
    W, [2016-08-09T16:29:40.548960 #51400]  WARN -- : Retrying: Errno::ECONNREFUSED: Connection refused - connect(2) for "Jeff-McCune.local" port 4433
    W, [2016-08-09T16:30:31.657935 #51400]  WARN -- : Retrying: Errno::ECONNREFUSED: Connection refused - connect(2) for "Jeff-McCune.local" port 4433
    F, [2016-08-09T16:32:13.969817 #51400] FATAL -- : ERROR Obtaining backup: {
      "error": "Ncio::Support::RetryAction::RetryException::Timeout",
      "message": "Ncio::Support::RetryAction::RetryException::Timeout",
      "backtrace": [
        "/Users/jeff/projects/puppet/ncio/lib/ncio/support/retry_action.rb:53:in `rescue in retry_action'",
        "/Users/jeff/projects/puppet/ncio/lib/ncio/support/retry_action.rb:45:in `retry_action'",
        "/Users/jeff/projects/puppet/ncio/lib/ncio/api/v1.rb:68:in `request_with_timeout'",
        "/Users/jeff/projects/puppet/ncio/lib/ncio/api/v1.rb:84:in `groups'",
        "/Users/jeff/projects/puppet/ncio/lib/ncio/app.rb:81:in `backup_groups'",
        "/Users/jeff/projects/puppet/ncio/lib/ncio/app.rb:57:in `run'",
        "/Users/jeff/projects/puppet/ncio/exe/ncio:5:in `<top (required)>'",
        "/Users/jeff/projects/puppet/ncio/.bundle/gems/ruby/2.1.0/bin/ncio:23:in `load'",
        "/Users/jeff/projects/puppet/ncio/.bundle/gems/ruby/2.1.0/bin/ncio:23:in `<top (required)>'",
        "/Users/jeff/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'",
        "/Users/jeff/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'",
        "/Users/jeff/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'",
        "/Users/jeff/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'",
        "/Users/jeff/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'",
        "/Users/jeff/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'",
        "/Users/jeff/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'",
        "/Users/jeff/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'",
        "/Users/jeff/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'",
        "/Users/jeff/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'",
        "/Users/jeff/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'",
        "/Users/jeff/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'",
        "/Users/jeff/.rbenv/versions/2.1.8/bin/bundle:23:in `load'",
        "/Users/jeff/.rbenv/versions/2.1.8/bin/bundle:23:in `<main>'"
      ]
    }
    F, [2016-08-09T16:32:13.970559 #51400] FATAL -- : ERROR: Timeout expired connecting to the console service.  Verify it is up and running.
    ERROR: Timeout expired connecting to the console service.  Verify it is up and running.

Improve 401 unauthenticated error

Without this patch the error message coming back from the RBAC service isn't
user friendly.  This patch addresses the problem by detecting the 401 response
and displaying the following error message:

    [vagrant@master1 ~]$ /opt/puppetlabs/puppet/bin/ncio backup
    ERROR: Make sure the --cert option value is listed in the certificate
    whitelist, and you are able to run puppet agent --test on the master.
    The certificate whitelist on the master is located at
    /etc/puppetlabs/console-services/rbac-certificate-whitelist

Resolves #7